export const samplePRDContent = `
<h1>Product Requirements Document</h1>
<p><em>Generated by Project Foundry AI</em></p>

<h2>1. Executive Summary</h2>
<p>This document outlines the requirements for a modern SaaS application designed to transform user ideas into production-ready development artifacts. The platform will serve product teams, solo founders, and development agencies looking to accelerate their development workflow.</p>

<h3>1.1 Product Vision</h3>
<p>To become the industry-standard tool for rapid prototyping and development planning, reducing the time from concept to code by 70%.</p>

<h3>1.2 Success Metrics</h3>
<ul>
  <li>Time to first PRD: &lt; 5 minutes</li>
  <li>Artifact generation accuracy: &gt; 90%</li>
  <li>User satisfaction score: &gt; 4.5/5</li>
  <li>Monthly active teams: 10,000+ by Q4 2025</li>
</ul>

<h2>2. User Personas</h2>

<h3>2.1 Solo Founder (Primary)</h3>
<p><strong>Background:</strong> Technical founder with limited resources looking to validate ideas quickly.</p>
<p><strong>Goals:</strong></p>
<ul>
  <li>Ship MVPs in weeks, not months</li>
  <li>Maintain consistent quality across projects</li>
  <li>Generate comprehensive documentation</li>
</ul>
<p><strong>Pain Points:</strong></p>
<ul>
  <li>Spending too much time on planning vs building</li>
  <li>Difficulty maintaining consistency across artifacts</li>
  <li>Context switching between tools</li>
</ul>

<h3>2.2 Product Manager (Secondary)</h3>
<p><strong>Background:</strong> Non-technical PM working with engineering teams.</p>
<p><strong>Goals:</strong></p>
<ul>
  <li>Communicate requirements clearly to developers</li>
  <li>Keep stakeholders aligned on scope</li>
  <li>Track dependencies visually</li>
</ul>

<h2>3. Core Features</h2>

<h3>3.1 Module Canvas</h3>
<p><strong>Description:</strong> Interactive visual workspace where users design project architecture by adding, removing, and connecting feature modules.</p>

<p><strong>Key Capabilities:</strong></p>
<ul>
  <li>Drag-and-drop module library with 50+ pre-built components</li>
  <li>Real-time status tracking (Include/Exclude/Maybe)</li>
  <li>Dependency visualization with directional edges</li>
  <li>Snap-to-grid alignment for clean layouts</li>
  <li>Export as JSON for version control</li>
</ul>

<p><strong>User Stories:</strong></p>
<ul>
  <li>As a user, I want to add an "Authentication" module so I can include user login in my project</li>
  <li>As a user, I want to mark modules as "Maybe" so I can decide later whether to include them</li>
  <li>As a user, I want to draw edges between modules so I can visualize dependencies</li>
</ul>

<h3>3.2 AI-Powered PRD Generation</h3>
<p><strong>Description:</strong> Automatically generate comprehensive Product Requirements Documents from module selections and brief descriptions.</p>

<p><strong>Key Capabilities:</strong></p>
<ul>
  <li>GPT-4 powered analysis of module graph</li>
  <li>Structured output with executive summary, user personas, features, and technical specs</li>
  <li>Read-only Tiptap viewer with professional formatting</li>
  <li>One-click export to Markdown</li>
  <li>Regeneration on module graph changes</li>
</ul>

<h3>3.3 Backend Specification</h3>
<p><strong>Description:</strong> Detailed database schema, API endpoints, and background jobs derived from PRD.</p>

<p><strong>Output Includes:</strong></p>
<ul>
  <li>Entity-Relationship Diagram (Mermaid format)</li>
  <li>Prisma schema with all models and relations</li>
  <li>REST/GraphQL API endpoint definitions</li>
  <li>Job queue specifications for async tasks</li>
  <li>Security considerations and RLS policies</li>
</ul>

<h3>3.4 Frontend Specification</h3>
<p><strong>Description:</strong> Component hierarchy, routing structure, and state management strategy.</p>

<p><strong>Output Includes:</strong></p>
<ul>
  <li>Next.js route structure</li>
  <li>React component tree with prop interfaces</li>
  <li>State management recommendations (Context, Zustand, Redux)</li>
  <li>API integration points</li>
  <li>Form validation schemas</li>
</ul>

<h3>3.5 Prompt Pack Export</h3>
<p><strong>Description:</strong> AI-optimized prompt bundles for Cursor, Claude Code, Lovable, and Bolt.new.</p>

<p><strong>Formats:</strong></p>
<ul>
  <li><strong>Cursor:</strong> .cursorrules format with ERD, user stories, and tech stack</li>
  <li><strong>Claude Code:</strong> Workflow-optimized with step-by-step implementation guide</li>
  <li><strong>Lovable:</strong> Frontend-focused with design system and component specs</li>
  <li><strong>Bolt.new:</strong> Full-stack rapid prototyping format</li>
</ul>

<h2>4. Technical Architecture</h2>

<h3>4.1 Tech Stack</h3>
<ul>
  <li><strong>Frontend:</strong> Next.js 14, React 18, TypeScript, Tailwind CSS, shadcn/ui</li>
  <li><strong>Backend:</strong> Next.js API Routes, Prisma ORM, PostgreSQL</li>
  <li><strong>AI:</strong> OpenAI GPT-4, Anthropic Claude 3.5 Sonnet</li>
  <li><strong>Infrastructure:</strong> Vercel (hosting), Supabase (database + auth), Redis (job queue)</li>
</ul>

<h3>4.2 Data Model</h3>
<p>Core entities include Project, ProjectGraph, Artifact (PRD, BackendSpec, etc.), Event (for audit trail), and DecisionLog.</p>

<h3>4.3 Event-Sourced Reconciliation</h3>
<p>When modules change, the system:</p>
<ol>
  <li>Emits <code>ModuleAdded/Removed/Updated</code> events</li>
  <li>Triggers reconciliation engine with dependency DAG</li>
  <li>Regenerates affected artifacts in order: Research → PRD → Backend → Frontend → UI → Mermaid → Prompts</li>
  <li>Runs invariant checks to ensure consistency</li>
</ol>

<h2>5. User Flow</h2>

<h3>5.1 Onboarding</h3>
<ol>
  <li>User signs up with email/Google</li>
  <li>Guided tour of Module Canvas</li>
  <li>Sample project pre-loaded</li>
  <li>First PRD generated in 30 seconds</li>
</ol>

<h3>5.2 Typical Session</h3>
<ol>
  <li>User creates new project from dashboard</li>
  <li>Enters title and elevator pitch in Settings</li>
  <li>Opens Canvas and adds modules (Auth, User Profile, Dashboard, etc.)</li>
  <li>Draws edges to show "Dashboard depends on Auth"</li>
  <li>Marks some modules as "Maybe" for later consideration</li>
  <li>Clicks "Regenerate" to trigger AI pipeline</li>
  <li>Reviews PRD in Tiptap viewer</li>
  <li>Navigates to Artifacts to see ERD and download Cursor prompt pack</li>
  <li>Exports ui-spec.json for Figma plugin</li>
</ol>

<h2>6. Non-Functional Requirements</h2>

<h3>6.1 Performance</h3>
<ul>
  <li>Canvas interactions: &lt; 16ms (60 FPS)</li>
  <li>PRD generation: &lt; 10 seconds</li>
  <li>Full artifact pipeline: &lt; 30 seconds</li>
  <li>Page load time: &lt; 2 seconds (Lighthouse score 90+)</li>
</ul>

<h3>6.2 Security</h3>
<ul>
  <li>Row-Level Security (RLS) on all database tables</li>
  <li>API keys stored in encrypted environment variables</li>
  <li>CSRF protection on all mutations</li>
  <li>Rate limiting: 100 requests/minute per user</li>
</ul>

<h3>6.3 Accessibility</h3>
<ul>
  <li>WCAG 2.1 AA compliance</li>
  <li>Keyboard navigation for all canvas operations</li>
  <li>Screen reader support with ARIA labels</li>
  <li>Focus indicators on all interactive elements</li>
</ul>

<h2>7. Release Plan</h2>

<h3>Phase 1: MVP (Current)</h3>
<ul>
  <li>✅ Module Canvas with React Flow</li>
  <li>✅ PRD Generation with AI agents</li>
  <li>✅ Basic artifact export</li>
  <li>✅ RAG-powered research system</li>
</ul>

<h3>Phase 2: Enhancement (Q1 2025)</h3>
<ul>
  <li>Real-time collaboration (multiplayer canvas)</li>
  <li>Version history and rollback</li>
  <li>Custom module templates</li>
  <li>Advanced analytics dashboard</li>
</ul>

<h3>Phase 3: Scale (Q2 2025)</h3>
<ul>
  <li>API for programmatic access</li>
  <li>Marketplace for community templates</li>
  <li>Integration with GitHub/GitLab</li>
  <li>Enterprise SSO and team management</li>
</ul>

<h2>8. Open Questions</h2>
<ul>
  <li>Should we support custom LLM providers (Azure, AWS Bedrock)?</li>
  <li>What's the pricing model? (Freemium with usage limits vs flat subscription)</li>
  <li>Do users need editable PRDs or read-only is sufficient?</li>
  <li>Should we build native mobile apps or keep it web-only?</li>
</ul>

<hr />

<p><em>This PRD was generated by Project Foundry AI on ${new Date().toLocaleDateString()}. For questions, contact the product team.</em></p>
`;
